apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-green.yaml
  - servive-blue.yaml
  - rollout.yml

configMapGenerator:
  - name: catalog-config
    files:
      - application.yml
    options:
      labels:
        app: catalog-service

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: catalog-service
    spec:
      template:
        spec:
          containers:
          - name: catalog-service
            image: ghcr.io/corlovito/catalog-service:b361facacc2063d775e81dc201a0784d9ce60cdb
