apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

resources:
  - service-green.yaml
  - servive-blue.yaml
  - rollout.yml

configMapGenerator:
  - name: catalog-config
    files:
      - application.yml
    options:
      labels:
        app: catalog-service
